name: Update Notion to GitHub
on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행하도록 예약

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install notion-py

    - name: Update Notion to GitHub
      run: python update_notion_to_github.py
